### ISSUE TITLE
Dreamweaver CS6 support with SVN 1.8

### ISSUE THREAD

**Issue by nabramovitz** [ChrisMcKee/svnweaver#5]
Does anyone know if svnweaver works with correctly with Dreamweaver CS6 64 bit and subversion 1.8 64 bit?

**Comment by ChrisMcKee** [comment]
`tsvnPATH = MM.regGetValue(regHIVE, regKEY, regVALUE);` is a string and can be set to your full path to tortoise (this is one place it will most likely be failing as msft kept moving around the x86 registry keys)
You can install pre all this subscription bollocks at adobe by installing the extension with the edited html+mxi 

I'd also advice setting https://github.com/ChrisMcKee/svnweaver/blob/master/SVNWeaver.htm#L121 to just var isSVN = true; to avoid issues with the .svn folder moving between 1.2 + 1.8
